sudo: false
dist: stretch
language: go
go:
  - "1.11"
stages:
- test
- build
- deploy
before_install:
- make dep
jobs:
  include:
  - stage: test
    name: "Verify"
    script: 
    - make checkfmt
    - make fmt
    - make vet 
    - make gocyclo
    - make golint 
    - make ineffassign
    - make misspell
  - name: "Unit Test"
    - make test
  - name: "Integration Test"
    script:
    - make integration-test
  - stage: build
    script: 
    - make linux 
    - make darwin 
    - make rpi
    - make windows
  - stage: deploy
    name: "GitHub Releases"
    script: skip
    deploy:
      provider: releases
      api_key: ${GITHUB_API_KEY}
      file: 
      - /home/travis/gopath/src/github.com/amimof/node-cert-exporter/out/node-cert-exporter-linux-amd64
      - /home/travis/gopath/src/github.com/amimof/node-cert-exporter/out/node-cert-exporter-darwin-amd64
      - /home/travis/gopath/src/github.com/amimof/node-cert-exporter/out/node-cert-exporter-linux-arm
      - /home/travis/gopath/src/github.com/amimof/node-cert-exporter/out/node-cert-exporter-windows-amd64.exe
      skip_cleanup: true
      draft: true
      on:
        tags: true